manager: Carlos Witte
teamroom: Eng.DevSpacesImport.QE
units: 
    - unit: https://app.crossover.com/x/dashboard/team/3230/1661414/team-metrics
automation: 
    product agnostic: yes
    product specific: 
        - product name: null
    description: Add QEPA feature to automatically reject or approve some tickets based on quality thresholds.
    effort: 42
    impact: 0.20