manager: !!str Bugra Kara
teamroom: !!str Eng.QAManualTesting
units: !!seq
    - unit: !!str https://jira.devfactory.com/browse/AUTO-1971
automation: !!map
    product agnostic: !!bool #boolean
    product specific: !!seq
        - product name: !!str #product names
    description: !!str
    effort: !!int #days
    impact: !!float #<%> at teamroom level
